<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	// require_once(APPLICATION_PATH.'/../'.PUBLICFOLDER.'/dompdf/dompdf_config.inc.php');
		
	$title = "Provisional Membership Certificate";
	$this->headTitle($title); 
	
	$farmer = new Farmer();
	$id = $request->id;
	
	$loggedinfarmer = new Farmer();
	$loggedinfarmer->populate($farmerid);
	$farmgroupid = $loggedinfarmer->getFarmGroupID();
	
	if(!isEmptyString($id)){
		$farmer->populate($id);
		$farm = $farmer->getFarm();
	}
?>
<script>
$(document).ready(function() {
	<?php if($request->print == 1){ ?>
		$("#headercontainer, #leftcolumn, .footer, #blankrow").remove().hide();
		$(".printpage").html($("#printer_page_action_buttons").html());
	<?php } ?>
	
	// trigger path to farmer report to be generated
	$("#id").change(function(){
		var id = $(this).val()
		var url = '<?php echo $this->baseUrl('report/certificate/id/'); ?>'+id;
		$("#generate").attr('href', url);
	});
});
</script>
<style>
#contentcolumn {
	min-height:600px;
}
#centercolumn {
	padding: 5px 0;
	width: 100%;
	margin-left:0;
	float:left;
}
#centercolumn h1, #centercolumn h2 {
	font-family:calibri, Telex, sans-serif;
}
#pageleft {
	margin:0 5px 0 0;
	width:100%;
	float:left;
	position:relative;
}
#pageleft .widgetsection {
	width:100%;
}
.widgetsection {
	margin-bottom:10px;
}
.widgetsection h3 {
	font-size:15px;
}
.contenttable {
	border:solid 1px #b3b3b3;
	border-collapse: separate;
 	*border-collapse: collapsed;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
}
.contenttable .control-label {
	width:auto;
	white-space:normal;
	text-align:left;
	display:block;
}
.contenttable h2 {
	margin: 0;
	padding: 8px 0 8px 0;
	line-height:auto;
	text-align: left;
	border-bottom:1px solid #c4c2c2;
	color:#498D0F;
	font-size:18px;
	width:100%;
	font-weight:bold;
	line-height:16px;
}
.contenttable#estimates thead tr td {
	font-weight:bold;
	font-size:11px;
	color:#000;
}
.contenttable#estimates thead tr td span {
	font-size:10px;
}
#outlength {
	width:72%;
}
.reportcontainer {
	height:auto; 
	min-height:750px; 
	display:block; 
	margin-top:10px;
	position:relative;
}
.reportlabel {
	display:inline-block;
	font-weight:bold;
	font-size:16px;
	padding-right:5px;
}
.reportfilter {
	margin-top:0; 
	float:right;
	margin-right:-10px;
}
.reportactions {
	position:absolute; 
	right:20px; 
	top:8px;
}
.reportlinks {
	margin-top:-10px;
}

#generate {
	margin-top:0;
}
.printpage {
	display:none;
}
pdfquicklinks {
	position:absolute; 
	left:10px; 
	top:8px;
}
.widgetsection h3.reportpagetitle {
	color:#282727;
}
.control-label {
	font-size:12px;
	white-space:nowrap;
	display:block;
	width:100%;
	text-align:left;
}
.table#data tr td {
	white-space:nowrap;
}
.paginatecustom {
	position:absolute;
	left:12px;
	top:10px;
	width:auto;
	text-align:left;
	float:left;
}
.pager {
	text-align:right;
}
<?php if($request->print == 1) { ?> 
#contentwrapper {
	margin: 10px 0 5px;
}
#centercolumn {
	float:left;
	width:90%;
}
#maincontainer.container {
	margin-left:20px;
	margin-top:10px;
}
#printer_page_action_buttons {
	margin:10px;
}
.hideonprint {
	display:none;
}
.printpage {
	margin:10px;
	display:block;
}
<?php } ?>

</style>
<form action="<?php echo $this->baseUrl("report/certificatesearch"); ?>" method="get" id="listform" class="form-search margin0" style="margin-top:5px;">
  <div id="centercolumn" class="reportpage">
  	<div class="printpage"></div>
    <div class="hideonprint" style="width:100%;">
        <?php if((isAdmin() || isFarmGroupAdmin())){ ?>
        	<table class="table table-condensed noborder margin0" style="width:980px;">
            	<tr>
                    <td style="width:60%;"></td>
                    <td>
                    	<?php if(isAdmin() || isFarmGroupAdmin()){ ?>
                            <span class="reportfilter pull-left">
                                <label class="reportlabel cal-font" style="vertical-align:top;">Farmer: </label>
                                <?php
                                    $farmerarray = getFarmers($farmgroupid);
                                    $farmerdropdown = new Zend_Form_Element_Select('id',
                                                        array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Browse Farmer>'), $farmerarray),								
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                                'class' => array('chzn-select', 'width180', 'novalidate')
                                                        )
                                                    );
                                    $farmerdropdown->setValue($request->getParam('id')); 
                                    echo $farmerdropdown->render(); 
                                  ?>&nbsp;&nbsp;
                                 <a id="generate" style="vertical-align:top;" href="<?php echo $this->baseUrl('report/certificate/id/'); ?>" class="btn btn-primary" title="Generate Report"><i class="icon-list-alt icon-white"></i> Generate</a>&nbsp;
                            </span>
                        <?php } ?>
                    </td>
                </tr>
            </table>
		<?php } ?>
    </div>
    <div class="pull-left" id="pageleft">
        	<?php if(isEmptyString($id)){ ?>
				<div class="widgetsection reportcontainer" style="width:980px;">
                	<h3 class="reportpagetitle"><?php echo $title; ?><span class="pagedescription pull-right">Select a Farmer to generate</span></h3>
                
            <?php } ?>
            <?php if(!isEmptyString($id)){
				$html = 
            	'<div class="widgetsection reportcontainer" style="width:980px;">
                	<h3 class="reportpagetitle">'.$title.'</h3>';
			?>
            	<?php if($request->print != 1){ ?>
					<?php $html .= '<span class="reportactions">
                        <a href="'.$this->baseUrl('report/certificate/id/'.$farmer->getID().'/print/1').'" target="_blank" class="btn btn-primary btn-mini" title="Print Report"><i class="icon-print icon-white"></i> Print</a>&nbsp;
                        <a href="'.$this->baseUrl('report/certificate/id/'.$farmer->getID().'/pdf/1').'" class="btn btn-primary btn-mini" title="View PDF Report"><i class="icon-list-alt icon-white"></i> PDF</a>&nbsp;
                        <a href="'.$this->baseUrl('report/certificate/id/'.$farmer->getID().'/download/1').'" class="btn btn-primary btn-mini" title="Print Report"><i class="icon-download icon-white"></i> Download</a>&nbsp;</span>';
                    ?>
                <?php } ?>
                <?php 
					$farmername = $farmer->getName();
					$startday =  date('jS');
					$startmonth = date('F');
					$startyear = date('Y');
					$certbg = $this->baseUrl('images/tempcert.png');
					$farmgrpname = isEmptyString($farmer->getFarmGroup()->getName()) ? "--": $farmer->getFarmGroup()->getName();
				
				$html .= 	
                '<div style="width:100%; height:auto; min-height:700px; overflow:auto; margin-bottom:10px; display:block; background-image: url('.$certbg.'); background-repeat:no-repeat; background-position:2px 3px; background-size: 975px auto; border:solid 1px #016c5c;">
                    <table class="table nohover noborder margin0" style="width:970px; height:690px;">
                        <tr>
                            <td class="yellowborder maxwidth" style="height:210px;">
                            </td>
                        </tr>
                        <tr>
                            <td class="redborder maxwidth">
                            	<table class="table nohover noborder margin0">
                                	<tr>
                                    	<td class="centeralign" style="font-weight: bold; font-size:2em; height:40px; padding-top:15px; color:#000;"><span style="color:#27843e;">P</span>rovisional <span style="color:#27843e;">C</span>ertificate of <span style="color:#27843e;">M</span>embership</td>
                                    </tr>
                                    <tr>
                                    	<td class="centeralign bolded" style="color:#27843e; font-size:18px; height:40px;">I certify that</td>
                                    </tr>
                                    <tr>
                                    	<td class="centeralign bolded" style="font-size:18px; padding-bottom:5px;"><span class="lineblocked centeralign" style="border-bottom:1px dashed #333333; width:70%; color:#000; padding-bottom:5px;">'.$farmername.'</span></td>
                                    </tr>
                                    <tr>
                                    	<td class="centeralign" style="color:#27843e; font-size:18px; height:25px;"></td>
                                    </tr>
                                    <tr>
                                    	<td class="centeralign" style="color:#27843e; font-size:18px; height:30px;">has on this <span class="lineblocked centeralign" style="border-bottom:1px dashed #333333; width:70px; color:#000;">'.$startday.'</span> day of <span class="lineblocked centeralign" style="border-bottom:1px dashed #333333; width:120px; color:#000;">'.$startmonth.'</span>
                                        	 the year of 
                                            <span class="lineblocked centeralign" style="border-bottom:1px dashed #333333; width:75px; color:#000;">'.$startyear.'</span> been accorded provisional membership to </td>
                                    </tr>
                                    <tr>
                                    	<td class="centeralign" style="font-size:18px; height:30px; color:#27843e;"><span class="lineblocked bolded" style="color:#8f1b1b;">Farmer Records Management Information Services</span></td>
                                    </tr>
									<tr>
                                    	<td class="centeralign" style="font-size:18px; height:30px; color:#27843e;"> under <span class="lineblocked centeralign" style="border-bottom:1px dashed #333333; width:auto; color:#000; padding:0 10px;">'.$farmgrpname.'</span> managed by FIT Uganda Ltd</td>
                                    </tr>
                                    <tr>
                                    	<td class="centeralign"><span class="lineblocked centeralign" style="border-bottom:1px dashed #333333; width:250px; height:40px;"></span></td>
                                    </tr>
                                    <tr>
                                    	<td class="centeralign" style="color:#27843e; font-size:18px;">DNA / Farm Group Representative</td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </div>';
				
				// echo page html
				if($request->pdf != 1){
					echo $html;
				}
				
				$pdf_html = '
					<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
					<html lang="en">
					<head>
						<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
					</head>
					<style>
						body {
							color: #555555;
							font-family: calibri, Telex, sans-serif;
							font-size: 13px;
							line-height: 18px;
						}
						.table-bordered {
						  border: 1px solid #dddddd;
						  border-left: 0;
						  border-collapse: separate;
						  *border-collapse: collapsed;
						   background-color: transparent;
							border-spacing: 0;
							max-width: 100%;
						}
						.table-bordered th,
						.table-bordered td {
						  border-left: 1px solid #dddddd;
						  border-top: 1px solid #dddddd;
						  padding: 2px 3px;
						  vertical-align: top;
						}
						.widgetsection {
							-moz-border-radius: 4px;	
							-webkit-border-radius:4px;
							-khtml-border-radius:4px;	
							border-radius:4px;	
							border-left: 4px solid #DDDDDD;
							border-right: 4px solid #DDDDDD;
							border-top: 2px solid #DDDDDD;
							border-bottom: 2px solid #DDDDDD;
							margin: 0 0 15px;
							padding: 0 5px 10px 5px;
							min-height:50px;
							height:auto;
							/*width:100%;*/
						}
						.widgetsection h3 {
							margin: 0;
							padding: 5px 5px 5px 5px;
							text-align: left;
							border-bottom:2px solid #E0E0E0;
							color:#498D0F;
							font-size:16px;
						}
						.widgetsection.height100 {
							min-height:100px;
						}
						.widgetsection.height150 {
							min-height:150px;
						}
						.widgetsection.height200 {
							min-height:200px;
						}
						.widgetsection.height300 {
							min-height:300px;
						}
						.widgetsection.height400 {
							min-height:400px;
						}
						.widgetsection.height500 {
							min-height:500px;
						}
						.widgetsection.height600 {
							min-height:600px;
						}
						
						#profileinfo, .profileinfo, #thumbinfo, .thumbinfo {
							position:relative;
							max-height: 195px;
							height:auto;
							width:165px;
							padding: 0;
							margin: 0 auto;
							border: 1px solid #C2C2C2;
							border: 1px solid rgba(0, 0, 0, 0.05);
							border-style: ridge;
							background-color:#f1f1f1;
							-webkit-border-radius: 3px;
							-moz-border-radius: 3px;
							border-radius: 3px;
						}
						#profileinfo.new_pic, .profileinfo.new_pic {
							box-shadow: 0 0 0 1px #F5F5F5, 0 0 0 2px #EBEBEB, 0 0 0 3px #E0E0E0, 0 0 0 4px #D6D6D6;
							-moz-box-shadow: 0 0 0 1px #F5F5F5, 0 0 0 2px #EBEBEB, 0 0 0 3px #E0E0E0, 0 0 0 4px #D6D6D6;
							-webkit-shadow: 0 0 0 1px #F5F5F5, 0 0 0 2px #EBEBEB, 0 0 0 3px #E0E0E0, 0 0 0 4px #D6D6D6;
						}
						#profileinfo #profileimage, .profileinfo .profileimage {
							margin-top:2px;
						}
	
						#centercolumn {
							padding: 5px 0;
							width: 78%;
						}
						#centercolumn h1, #centercolumn h2 {
							font-family: calibri, Telex, sans-serif;
						}
						#pageleft {
							margin:0 5px 0 0;
							width:98%;
							float:left;
						}
						#pageleft .widgetsection {
							width:100%;
						}
						.widgetsection {
							margin-bottom:10px;
						}
						.widgetsection h3 {
							font-size:15px;
						}
						.contenttable {
							border:solid 1px #b3b3b3;
							border-collapse: separate;
							*border-collapse: collapsed;
							-webkit-border-radius: 4px;
							-moz-border-radius: 4px;
							border-radius: 4px;
							width:100%;
						}
						.contenttable .control-label {
							width:auto;
							white-space:normal;
							text-align:left;
							display:block;
							color: #333333;
							margin-bottom: 5px;
							font-size: 13px;
							line-height: 18px;
							font-weight: bold;
						}
						.contenttable h2 {
							margin: 0;
							padding: 8px 0 8px 0;
							line-height:auto;
							text-align: left;
							border-bottom:1px solid #c4c2c2;
							color:#498D0F;
							font-size:18px;
							width:100%;
							font-weight:bold;
							line-height:16px;
							calibri,Telex,sans-serif;
						}
						.contenttable#estimates thead tr td {
							font-weight:bold;
							font-size:10px;
							color:#000;
						}
						.contenttable#estimates thead tr td span {
							font-size:10px;
						}
						#printer_page_action_buttons {
							display:block;
							margin:10px;
						}
						table#crops {
							height:180px;
						}
						table#crops ul#croplist {
							margin:0;
							margin-left: -15px;
							height:130px;
						}
						.reportcontainer {
							height:auto; 
							min-height:800px; 
							display:block; 
							margin-top:10px;
							position:relative;
						}
						.reportlabel {
							display:inline-block;
							font-weight:bold;
							font-size:16px;
							padding-right:5px;
						}
						.reportfilter {
							margin-top:0; 
							float:right;
							margin-right:-10px;
						}
						#generate, .printpage, .pdfquicklinks, .reportactions{
							display:none;
						}
						.widgetsection h3.reportpagetitle {
							color:#282727;
						}
					</style>
					<body>
						<div style="width:100%;">
							'.$html.'
						</div>
					</body>
					</html>
				';
				
				$temp_file_name = '';
				if($request->download == 1 || $request->pdf == 1){
					$timestamp = time().rand(100, 5000);
					$temp_file_name = ($timestamp).".pdf";
					$temp_file_text = ($timestamp).".txt";
		
					$dompdf = new DOMPDF();
					$dompdf->load_html($pdf_html);
					
					$dompdf->render();
					$output = $dompdf->output();
					// debugMessage($output);
					$path = APPLICATION_PATH.DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."public".DIRECTORY_SEPARATOR."dompdf".DIRECTORY_SEPARATOR."temp".DIRECTORY_SEPARATOR.$temp_file_name;
					$path_txt = APPLICATION_PATH.DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."public".DIRECTORY_SEPARATOR."dompdf".DIRECTORY_SEPARATOR."temp".DIRECTORY_SEPARATOR.$temp_file_text;
					$relativepathtodocument = $this->serverUrl($this->baseUrl('dompdf/temp/'.$temp_file_name));
					file_put_contents($path, $output);
					// file_put_contents($path_txt, $pdf_html);
				}
			
		?>	
        <?php if($request->pdf == 1){ ?>
      		<iframe style ="margin: 0; width: 100%; height: 840px;" src="http://docs.google.com/gview?url=<?php echo $relativepathtodocument; ?>&embedded=true" frameborder="0"></iframe>
      	<?php } } ?>
		</div>
  	</div>
</div>
</form>
<script>
$(document).ready(function() {
<?php if($request->download == 1){ ?>
	var url = '<?php echo $this->baseUrl('download/index/type/certificate/filename/'.encode($temp_file_name)); ?>';
	window.location.href = url;
<?php } ?>
});
</script>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>