<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$farmer = new Farmer();
	
	$theid = decode($request->id);
	if(isEmptyString($theid)){
		$theid = $farmerid;
	}
	$farmer->populate($theid);
	$id = $farmer->getID();
	
	$id = $farmer->getID();	
	$name = $farmer->getName();
	$firstname = $farmer->getFirstName();
	
	# profile for one viewing
	$isme = false;
	if($farmerid == $farmer->getID()){
		$isme = true;
	}
	
	$hasfarm = false;
	$hasmultiplefarms = false;
	$hasnofarm = false;
	$countfarms = $farmer->getFarms()->count();
	if($countfarms == 0){
		$farmlabel = "Setup Farm";
		$hasnofarm = true;
	}
	if($countfarms == 1){
		$hasfarm = true;
		$farmid = $farmer->getFarms()->get(0)->getID();
		$farmlabel = "Manage Farm";
	}
	if(!isEmptyString($farmer->getFarm()->getID())){
		$hasfarm = true;
		$farmid = $farmer->getFarm()->getID();
	}
	if($countfarms > 1){
		$hasmultiplefarms = true;
		$farmlabel = "Manage Farms";
	}
	
	$request->setParam('tab', 'subscription');
	
	$isfarmer = false;
	$isfarmgroup = false;
	$type = $request->self;
	
	$payment = new Payment();
	$payment->setTrxDate(date('Y-m-d'));
	$payment->setUserID($farmer->getUserID());
	$payment->setFarmerID($farmer->getID());
	$payment->setPhone($farmer->getUser()->getPhone());
	$payment->setStem(2);	
	$payment->setItem(2);
	$payment->setAmount($payment->getDefaultFarmerAmount());
	
	$plan = new MembershipPlan(); 
	$plan->populate(2); 
	
	$posturl= '';
	$step = $request->step;
	if(isEmptyString($step)){
		$step = 1;
	}
		
	$title = $payment->getFarmer()->getName();
	$formtitle = "New Payment";	
	$this->headTitle($title);
	
?>
<script>
$(document).ready(function() {
	<?php //if($step == 2){ ?>
		
	<?php //} ?>
	
	// form wizard
	$('#paynowform').stepy({
		backLabel:	'Back',
		block:		true,
		errorImage:	false,
		nextLabel:	'Continue',
		titleClick:	true,
		validate:	true,
		back: function(index) {
			$("#paynowform-next-1").hide();
			if(index == 2){
				$("#step2auth").show();
			} else {
				$("#step2auth").hide();
			}
		},
		next: function(index) {
			$("#paynowform-next-1").hide();
			if(index == 2){
				$("#step2auth").show();
			} else {
				$("#step2auth").hide();
			}
			$("#step2auth").click(function(e){
				// e.preventDefault();
				if(isStep2valid()){
					// no validation errors
					$("div#pin_error").html('');
					var phone = $("#phone").val();
					var pin = $("#pin").val();
					var successurl = $("#step2_successurl").val();
					var step2authaction = '<?php echo $this->baseUrl('payment/step2auth/id/'.encode($payment->getFarmerID())); ?>/phone/'+phone+'/pin/'+pin+'/successurl/'+successurl;
					$(location).attr('href', step2authaction);
				} 
			});
			switch (index){
				case '2':

					break; 
			}
		}
	});
	
	$(".button-back").html('').prepend('<i class="icon-arrow-left icon-white"></i> Back').addClass('btn btn-primary btn-large');
	$(".button-next").html('').prepend('<i class="icon-arrow-right icon-white"></i> Continue').addClass('btn btn-primary btn-large'); 
	$(".finish").html('').prepend('<i class="icon-ok icon-white"></i> Continue').addClass('btn btn-primary btn-large pull-left');
	$(".step legend, .paynowform-next-1, #step2auth").hide();
	$(".step").attr('title','');
	
	var step = '<?php echo $step; ?>';
	$('#paynowform').stepy('step', step);
	
	<?php if($step == 3){ ?>
		// change name of step 3 button
		$("#paynowform-next-2").html('').prepend('<i class="icon-arrow-right icon-white"></i> Pay Now').addClass('btn btn-primary btn-large');
		// compute amout 
		computeRenewAmount();
		$("#period").change(function(e){
			computeRenewAmount();
		});
		
		// 
	<?php } ?>
	$('span#computedunit').html('1,200');
	
	function isStep2valid(){
		var value = $("#pin").val();
		if(isEmptyString(value)){
			$("div#pin_error").html('<div class="alert alert-error">Please enter PIN Code</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px','margin-top': '5px'});
			return false;
		}
		if(value.length < 4 && value.length > 4){
			$("div#pin_error").html('<div class="alert alert-error">Please enter a Valid PIN Code</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px','margin-top': '5px'});
			return false;
		}
		return true;
	}
	
	function addCommas(x) {
		return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
	}
	
	function computeRenewAmount(){
		var selectedperiod = $('#period').val();
		// alert(addCommas(selectedperiod * 1200));
		var unitcost = 1200;
		$('span#computedunit').html(addCommas(unitcost));
		$('span#computedamount').html(addCommas(selectedperiod * unitcost));
		var total = $('#trxfees').val();
		$('span#computedtotal').html(addCommas(parseInt(total) + parseInt((selectedperiod * unitcost))));
	}
}); 
</script>
<style>
.button-next, .finish {
	float:left;
	margin-left:15px;
}
.stepy-titles li {
	padding: 10px 10px 10px 5px;
	font-size:13px;	
	width: 22%;
	color:#ccc;
}
.stepy-titles li span {
	margin-top:15px;
	font-size:14px;
}
</style>
<?php if(!isFarmer()){ ?>
<h1><?php echo $title; ?></h1>
<?php } ?>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/farmer/farmerleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">
    	<?php require APPLICATION_PATH."/views/scripts/farmer/tabstop.phtml"; ?>
		<div id="subscription" class="makerelative">
        	<h2><?php echo $formtitle; ?></h2>
            <form class="form-horizontal well" id="paynowform" action="<?php echo $posturl; ?>" method="post" style="width:97%;">
				<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>	
                <fieldset title="Requirements" id="summary">
                    <legend>Step 1</legend>
                    <table class="table nohover">
                        <tr>
                           <td colspan="2">
                           		<div style="padding:10px 10px; width:80%; font-size:14px;" class="alert alert-info margin5">
                                    To effect a Payment via the FARMIS Payment System, please note carefully the following requirements.<br /><br />
                                    1. You should have a valid account with the <b>FARMIS Trading Platform (FTP)</b>. If you do not have an account <a href="javascript: void(0);">click here</a>.<br /><br />
                                    2. You should have some money on your payment to renew or make a payment. We recommend that you maintain atleast UGX 10,000 so as to renew your subscription. For more information on how to credit your FTP Account, <a href="javascript: void(0);">click here</a>.<br /><br />
                                    3. TBD<br /><br />
                                    4. TBD<br /><br />
                                </div>
                           </td>
                        </tr>
                    </table>    
                </fieldset>
                <fieldset title="Validate Account" id="validateaccount" class="makerelative">
                    <legend>Step 2</legend>
                    <table class="table nohover">
                        <tr>
                           <td colspan="2" style="padding-bottom:30px;">
                           		<div style="padding:10px 10px; width:80%; font-size:14px;" class="alert alert-info margin5">
                                    Specify your Trading Platform PIN Code and click validate.
                                </div>
                           </td>
                        </tr>
                        <tr>
                           <td style="width:20%; padding-bottom:30px;"><label class="control-label">Phone Number:</label></td>
                           <td><?php echo $farmer->getUser()->getPhone(); ?><input type="hidden" id="phone" name="phone" value="<?php echo $farmer->getUser()->getPhone(); ?>" /><div id="phone_error"></div></td>
                        </tr>
                        <tr>
                           <td style="padding-bottom:70px;"><label class="control-label">Trading Platform PIN:</label><span class="pagedescription">(4 digits)</span></td>
                           <td><input name="pin" id="pin" type="password" autocomplete="off" maxlength="4" class="width75 xhastooltip" ssssvalue="" title="<?php //echo $this->translate("farmer_password_tooltip"); ?>" /><div id="pin_error"></div></td>
                        </tr>
                    </table>  
                </fieldset>
                <fieldset title="Validate Payment" id="validatepayment">
                    <legend>Step 3</legend>
                    <div class="well lighter row marginleft0" style="min-height:100px; width:94%; margin:10px; background-color:#fff;">
                        <h3 class="well-legend">Account Summary</h3>
                        <table class="table">                       
                            <tr>
                                <td width="20%"><label class="control-label">Name:</label></td>
                                <td><?php echo $payment->getFarmer()->getUser()->getName(); ?></td>
                            </tr>
                            <tr>     
                                <td><label class="control-label">Phone:</label></td>
                                <td><?php echo $payment->getFarmer()->getUser()->getPhone(); ?></td>
                            </tr>
                            <tr>
                                <td><label class="control-label">Available Balance (UGX):</label></td>
                                <td><?php echo /*$plan->getUnitAmount();*/'65,500'; ?></td>
                            </tr>
                        </table>
                    </div>
                    <div class="well lighter row marginleft0" style="min-height:100px; width:94%; margin:10px; background-color:#fff;">
                        <h3 class="well-legend">Payment Instructions</h3>
                        <table class="table">                       
                            <tr>
                                <td width="20%"><label class="control-label">Subject:</label></td>
                                <td><?php echo 'FARMIS Premium Subscription Account Renewal'; ?></td>
                            </tr>
                            <tr>     
                                <td><label class="control-label">Unit Cost (UGX):</label></td>
                                <td><span id="computedunit"></span> Per Month</td>
                            </tr>
                            <tr>
                                <td><label class="control-label">Subscription Period: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><?php
                                        $univalues = array('12'=>'12 Months', '6'=>'6 Months', '3'=>'3 Months');
                                        $unitdropdown = new Zend_Form_Element_Select('period',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $univalues),								
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('span2','width100','hastooltip', 'selectrequired'),
                                                                'title' => $this->translate("payment_renewed_period_tooltip")
                                                            )
                                                        );
                                        $unitdropdown->setValue('6'); 
                                        echo $unitdropdown->render(); 
                                    ?><div id="period_error"></div></td>
                            </tr>
                            <tr>
                                <td><label class="control-label">Total Cost (UGX):</label></td>
                                <td><span id="computedamount"></span></td>
                            </tr>
                            <tr>
                                <td><label class="control-label">Transaction Fees (UGX):</label></td>
                                <td><input type="hidden" class="hidden" name="trxfees" id="trxfees" value="0" />0</td>
                            </tr>
                            <tr>
                                <td><label class="control-label">Amount Due (UGX):</label></td>
                                <td><span id="computedtotal">0</span><input type="hidden" class="hidden" name="amount" id="amount" value="0" /></td>
                            </tr>
                        </table>
                    </div>
                </fieldset>
                <fieldset title="Complete Transaction" id="completepayment">
                    <legend>Step 4</legend>
                    <table class="table nohover">
                        <tr>
                           <td colspan="2"></td>
                        </tr>
                    </table>  
                </fieldset>
                <button type="button" class="btn btn-primary btn-large step2auth hidden" id="step2auth" style="position:absolute; left:160px; bottom:55px;"><i class="icon-arrow-right icon-white"></i> Validate</button>
                <button type="button" class="btn btn-primary btn-large step2auth hidden" id="step3pay" style="position:absolute; left:160px; bottom:55px;"><i class="icon-arrow-right icon-white"></i> Pay Now</button>
                <input type="hidden" id="step2_successurl" name="step2_successurl" value="<?php echo encode($this->baseUrl('payment/paynow/id/'.encode($payment->getFarmerID()).'/step/3')); ?>" />
                <button type="submit" class="btn btn-primary btn-large finish" id="complete"><i class="icon-arrow-right icon-white"></i> Complete</button>
                <input type="hidden" id="id" name="id" value="<?php echo encode($payment->getID()); ?>" />
                <input type="hidden" id="stem" name="stem" value="<?php echo $payment->getStem(); ?>" />
                <input type="hidden" id="farmgroupid" name="farmgroupid" value="<?php echo $payment->getFarmGroupID(); ?>" />
                <input type="hidden" id="farmerid" name="farmerid" value="<?php echo $payment->getFarmerID(); ?>" />
                <input type="hidden" id="userid" name="userid" value="<?php echo $payment->getUserID(); ?>" />
                <input type="hidden" name="<?php echo SUCCESS_MESSAGE; ?>" value="global_save_success" />
                
            </form>
        </div>
        <?php require APPLICATION_PATH."/views/scripts/farmer/tabsbottom.phtml"; ?> 
    </div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>