<?php
	require_once APPLICATION_PATH.'/includes/header.php';
		
	$user = new UserAccount();
	$farmgroup = new FarmGroup();
	
	$user->populate($userid);
	if(isFarmer() || isFarmGroupAdmin()){
		$user->populate($userid);
		
		$countcrops = $user->getCrops()->count();
		$countseasons = $user->getSeasons()->count();

		$seasonid = '';
		$seasonurl = 'javascript: void(0)';
		
		$step1_1_counter = $user->getStep1_1_Status();
		$step1_3_counter = $user->getStep1_3_Status();
		$step1_4_counter = $user->getStep1_4_Status();
		$step2_1_counter = $user->getStep2_1_Status();
		$step2_2_counter = $user->getStep2_2_Status();
		$step2_4_counter = $user->getPreseasons()->get(0)->getPreseasonEstimatesStatus();
		$step3_1_counter = $user->getSeasons()->count();
		$step3_2_counter = 0;
		$step3_3_counter = 0;
		$step3_4_counter = 0;
		
		$seasonurl = $this->baseUrl('season/index/userid/'.encode($user->getID()));
		$season = $user->getSeasons()->get(0);
		$seasonid = $season->getID();
		if(!isEmptyString($seasonid)){
			$timeline = $season->getTimeLineDetails();
			$step3_2_counter = count($timeline);
			$seasonurl = $this->baseUrl('season/view/id/'.encode($seasonid));
			// season expenses
			$step3_3_counter = $season->getTotalExpenses();
		}
		
		$inventories = $user->getInventoryDetails();
		$step3_4_counter = $inventories->count();
		
		if(isFarmGroupAdmin()){
			$farmgroup = $user->getFarmGroup();
			// debugMessage($farmgroup->toArray());
		}
	}
	
	$title = $this->translate("dashboard_pagetitle");
	$this->headTitle($title); 
?>
<script>
$(document).ready(function(){
	
});
</script>
<style>

</style>	
<div class="blocked clear maxwidth">
	<?php require APPLICATION_PATH."/views/scripts/index/leftcolumn.phtml"; ?>
    <div id="centercolumn">
    	<!--=== Page Header ===-->
        <div class="page-header">
            <div class="page-title">
                <h3>Dashboard</h3>
                <span><?php echo greatUser($user->getFirstName()); ?>!</span>
            </div>
            <ul class="page-stats dashbd">
                <li><div class="summary"><span>My Location</span><h3 id="location_html"><?php echo !isEmptyString($user->getLocationID()) ? $user->getLocation()->getName() : 'Kampala'; ?></h3></div>
                </li>
                <li><div class="summary floatleft"><span>Current Condition</span><h3 id="summary_html" class="weatherdata"></h3></div>
                    <div class="floatright"><canvas id="icon1" width="48" height="48" class="blocked floatright"></canvas></div>
                </li>
                <li><div class="summary"><span>Temperature</span><h3 id="temp_html" class="weatherdata"></h3></div></li> 
                <li><div class="summary"><span>Pressure</span><h3 id="pressure_html" class="weatherdata"></h3></div></li> 
                <li><div class="summary"><span>Humidity</span><h3 id="humidity_html" class="weatherdata"></h3></div></li>        
                <li><a class="gonowhere btn btn-default btn-xs" id="weather"><i class="icon-refresh"></i></a></li>
            </ul>
        </div>
    </div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
