<?php
	require_once APPLICATION_PATH.'/includes/header.php';

	$controller = $request->getControllerName();
	$action = $request->getActionName();
	if($controller == 'farmer' && isEmptyString($request->tab)){
		$request->setParam('tab', 'basics'); 
	}
	// debugMessage($farmer->toArray());
?>
<script>
$(document).ready(function() {
	// override default tab
	<?php if(!isEmptyString($request->tab)){ ?>
		$("#tabs").tabs({ selected:'<?php echo $request->tab; ?>', fx: {opacity: 'toggle'} });	   
	<?php } ?>
	$('#tabs').tabs({
		// the selected tab
		selected: '<?php echo $request->tab; ?>'
	});
	
	<?php if($controller != 'farmer'){ ?>
		$("#tabs ul li#tab_summary").removeClass("ui-state-active").removeClass("ui-tabs-selected");
	<?php } ?>
	
	$("#tabs ul#leftnav li a").click(function(e){
		var currentclass = $(this).attr('class');
		var oldclass = '<?php echo $request->tab; ?>';
		if(currentclass != oldclass || currentclass == 'subscription'){
			$(".form-horizontal."+currentclass).html("<a id='loading' class='xhidden' style='text-align:center; display:block; margin-top:75px;'><span style='display:block; margin-bottom:15px; font-weight:bold;'>Loading...</span><img style='margin-left:-10px;' src='<?php echo $this->baseUrl('images/farmisloader.gif'); ?>' /></a>").css({'display':'block'});
			var url = '';
			var controller = '<?php echo $controller; ?>';
			var action = '<?php echo $action; ?>';
			
			if(controller == 'farmer' && action == 'index'){
				var url = "<?php echo $this->baseUrl("farmer/index/id/".encode($farmer->getID())."/tab/"); ?>"+currentclass;
			}
			if((controller == 'farmer' && action == 'view') || action == 'picture' || controller == 'payment'){
				var url = "<?php echo $this->baseUrl("farmer/view/id/".encode($farmer->getID())."/tab/"); ?>"+currentclass;
			}
			
			if(currentclass == 'farm'){
				<?php if($hasfarm){ ?>
					<?php if($hasmultiplefarms){ ?>
						var url = "<?php echo $this->baseUrl('farm/list'); ?>";
					<?php } else { ?>
						var url = "<?php echo $this->baseUrl('farm/view/id/'.encode($farmid)); ?>";
					<?php } ?>
				<?php } else { ?>
					var url = "<?php echo $this->baseUrl('farm/index/farmerid/'.encode($farmer->getID())); ?>";
				<?php } ?>
				<?php if($farmer->isFarmGroupManager()){ ?>
					var url = "<?php echo $this->baseUrl('farmgroup/view/id/'.encode($farmer->getFarmGroupID())); ?>";
				<?php } ?>
			}
			if(currentclass == 'subscription'){
				var url = "<?php echo $this->baseUrl('payment/list/id/'.encode($farmer->getID())); ?>";
			}
			if(!isEmptyString(url)){
				location.href = url;  
			}
		}
	});
	
	$("#tabs").tabs().addClass('ui-tabs-vertical ui-helper-clearfix');
	$("#tabs li").removeClass('ui-corner-top').addClass('ui-corner-left');
	
}); 
</script>
<div class="span3 marginleft0" id="left">    
    <div class="well" id="profiletop">
        <div id="profileinfo"> 
			<?php if($isme || isFarmGroupAdmin() || isAdmin()){ ?>
                <a href="<?php echo $this->baseUrl('farmer/picture/id/'.encode($farmer->getID()).'/type/photo'); ?>" class="editpic" title="Update Profile Photo"><img id="profileimage" src="<?php echo $farmer->getUser()->getMediumPicturePath(); ?>" /><pre id="uploadlink" class="hide absoluteupload"><i class="icon-pencil"></i> Upload Photo</pre></a>
            <?php } else { ?>
                <img id="profileimage" src="<?php echo $farmer->getUser()->getMediumPicturePath(); ?>" alt="Update Profile Photo" />
            <?php } ?>
        </div>
    </div>
    <ul id="leftnav" style="width:97%;">
        <li id="tab_basics"><a href="#basics" class="basics">Profile Summary </a></li>
        <li id="tab_contacts"><a href="#contacts" class="contacts">Contacts and Address</a></li>
        <li id="tab_personal"><a href="#personal" class="personal">Personal Bio Data</a></li>
        <?php if($farmer->isFarmer()){ ?>               
        <li id="tab_farm"><a href="#farm" class="farm"><?php echo $farmlabel; ?></a></li>
        <?php } ?>
        <?php if($farmer->isFarmGroupManager()){ ?>
        <li id="tab_farm"><a href="#farm" class="farm">Manage Farm Group</a></li>
        <?php } ?>
        <li id="tab_subscription"><a href="#subscription" class="subscription">Subscription</a></li>
        <li id="tab_account"><a href="#account" class="account">Account Settings</a></li>   
    </ul>
</div>
