<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = ($this->translate("useraccount_pagetitle_signup"));	
	$this->headTitle($title); 
	
	// the usermaking the payment
	$useraccount = new UserAccount();
	$useraccount->populate(decode($request->id)); 
	$posturl = $this->baseUrl("signup/processstep3"); 
	
?>
<script>
	$(document).ready(function() {		
	
		// if skip button is clicked, trigger a submit with flag to skip payment processing
		$("#paypal").click(function(){		
			// then submit the form
			$('#paymentform').submit();
			return true;
		});
		
		$("#step3form").validate({		
			// define the validation rules one field at a time
			rules: {				
				first_name: "required",
				last_name: "required",
				credit_card_type: "required",
				credit_card_number: "required",
				expire_date_month: "required",				
				expire_date_year: "required",				
				cvv2_code: "required",
				address1: "required",
				/*address2: "required",*/
				country_code: "required",
				state: "required",
				city: "required",
				postal_code: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {												
				first_name: "<?php echo $this->translate("billing_first_name_error"); ?>",
				last_name: "<?php echo $this->translate("billing_last_name_error"); ?>",
				credit_card_type: "<?php echo $this->translate("billing_credit_card_type_error"); ?>",
				credit_card_number: "<?php echo $this->translate("billing_credit_card_number_error"); ?>",				
				expire_date_month: "<?php echo $this->translate("billing_expire_date_month_error"); ?>",				
				expire_date_year: "<?php echo $this->translate("billing_expire_date_year_error"); ?>",
				cvv2_code: "<?php echo $this->translate("billing_cvv2_code_error"); ?>",
				address1: "<?php echo $this->translate("billing_streetaddress_error"); ?>",
				/*address2: "<?php // echo $this->translate("billing_streetaddress2_error"); ?>",*/
				country_code: "<?php echo $this->translate("billing_country_code_error"); ?>",
				state: "<?php echo $this->translate("billing_state_error"); ?>",
				city: "<?php echo $this->translate("billing_city_error"); ?>",
				postal_code: "<?php echo $this->translate("billing_postal_code_error"); ?>"
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){
					case 'country_code':
						error.appendTo("#country_error")
						break;
					case 'state':
						error.appendTo("#state_error")
						break;										
					default:
						error.insertAfter(element);
						break;
				}			
			}
		});
		
		// trigger state field depending on the country
		//$("#usstates").hide();
		//$("#nonusstates").show();
		$("#country_code").change(function(){
			if($(this).val() == 'US'){
				disableContainerByID("nonusstates");
				enableContainerByID("usstates");				
			} else {
				disableContainerByID("usstates");
				enableContainerByID("nonusstates");						
			}
			$("#state").val('');
			$("#notusstate").val('');
		});
		
		// hide the nonusstate by default
		// $("#nonusstates").hide();
		disableContainerByID("usstates");
		disableContainerByID("nonusstates");
		// pay by credit card should be default payment method
		//$("#payment_type_credit_card").click();
		
		// show different form fields depending on the payment option selected	
		$(".payment_type_paypal").click(function(){
			//alert("Payment type: paypal");
			disableContainerByID("creditcardpayment");
			disableContainerByID("city_zip");
			//enableContainerByID("paypalpayment");
			disableContainerByID("creditcardbuttons");
			enableContainerByID("paypalbuttons");
			disableContainerByID("trialbuttons");
			disableContainerByID("usstates");
			disableContainerByID("nonusstates");
		});	
		$(".payment_type_credit_card").click(function(){
			//alert("Payment type: credit card");
			//disableContainerByID("paypalpayment");	
			enableContainerByID("creditcardpayment");
			enableContainerByID("city_zip");
			enableContainerByID("creditcardbuttons");
			disableContainerByID("paypalbuttons");
			disableContainerByID("trialbuttons");
			
			// if existing user populate existing state depending on the country
			if($("#country_code").val() == 'US'){
				disableContainerByID("nonusstates");
				enableContainerByID("usstates");
			} else {
				disableContainerByID("usstates");
				enableContainerByID("nonusstates");	
			}
			// recompute page height
			// resize page
			resizePageForm();
		});
		$(".freetrial").click(function(){
			//alert("Payment type: paypal");
			disableContainerByID("creditcardpayment");
			disableContainerByID("city_zip");			
			disableContainerByID("creditcardbuttons");
			disableContainerByID("paypalbuttons");
			disableContainerByID("usstates");
			disableContainerByID("nonusstates");
			enableContainerByID("trialbuttons");	
		});	
		
		// recompute page height
		function recomputeHeights(){
			equalHeight($("#step3form, #contentcolumn"));
			$("#contentcolumn").css({'height': $("#contentcolumn").height() + 150});
		}
	}); 
	
	
</script>
<style>
body#publicbody #contentcolumn {
	margin-top:45px;
 *margin-top:5px;
	padding-left:200px;
}
table.formtable {
	width:590px;
	border:1px solid #AAAAAA;
	margin-top:0;
}
table.formtable td {
	border-right:none;
}
table.formtable td.label {
	border-right:1px solid #AAAAAA;
}
select.chzn-select {
	min-width:259px;
	width:259px;
 	*width:260px;
}
</style>
<h1><?php echo $title; ?></h1>
<?php if ($sessionhaserror) { ?>
<label class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></label>
<?php } ?>
<form action="<?php echo $posturl; ?>" method="post" name="step3form" id="step3form">
  <table class="formtable">
    <thead>
      <tr>
        <td colspan="2"><?php echo $this->translate("useraccount_section_signup_step3"); ?></td>
      </tr>
    </thead>
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_signupamount_label"); ?> ($):</td>
      <td><span class="amount_text"><?php echo $this->currency($config->billing->writermonthlyrate); ?></span>/month
        <input type="hidden" name="amount" value="<?php echo $config->billing->writermonthlyrate; ?>" />
        <input type="hidden" name="ipaddress" value="<?php echo $_SERVER['REMOTE_ADDR']; ?>" /></td>
    </tr>
    <tr>
      <td colspan="2"><h2><?php echo $this->translate("billing_section_payment_method"); ?></h2></td>
    </tr>
    <tr>
      <td class="label"><input type="radio" id="payment_type_paypal" class="payment_type_paypal" name="payment_type" value="paypal" /></td>
      <td><a href="javascript: doNothing();" class="payment_type_paypal"><img src="<?php echo $this->baseUrl("images/btn_xpressCheckout.gif"); ?>" alt="We accept payments through Paypal" /></a></td>
    </tr>
    <tr>
      <td class="label"><input type="radio" id="payment_type_credit_card" class="payment_type_credit_card" name="payment_type" value="credit_card"></td>
      <td><a href="javascript: doNothing();" class="payment_type_credit_card"><img src="<?php echo $this->baseUrl("images/btn_cc_vmad.gif"); ?>" alt="Pay using your Credit or Debit Card" /></a></td>
    </tr>
    <tr>
      <td class="label"><input type="radio" id="freetrial" class="freetrial" name="payment_type" value="0"></td>
      <td><a href="javascript: doNothing();" class="freetrial"><?php echo $this->translate("billing_label_7_day_trial"); ?></a></td>
    </tr>
    <tbody id="creditcardpayment" class="hidden">
      <tr>
        <td colspan="2"><h2><?php echo $this->translate("billing_section_credit_debit_card_information"); ?></h2></td>
      </tr>
      <tr>
        <td class="label"><?php echo $this->translate("useraccount_firstname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><input name="first_name" id="first_name" type="text" value="<?php echo $useraccount->getFirstName(); ?>" />
          <span class="small">(as it appears on card)</span></td>
      </tr>
      <tr>
        <td class="label"><?php echo $this->translate("useraccount_lastname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><input name="last_name" id="last_name" type="text" value="<?php echo $useraccount->getSurname(); ?>" />
          <span class="small">(as it appears on card)</span></td>
      </tr>
      <tr>
        <td class="label"><?php echo $this->translate("billing_cardtype_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><?php		
                $creditcardtypelookup = new LookupType(); 				
                $creditcardtypelookup->setName("CREDIT_CARD_TYPES");				
                $genredropdown = new Zend_Form_Element_Select('credit_card_type',
                                    array(
										'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $creditcardtypelookup->getOptionValuesAndDescription()),						
										'view' => new Zend_View(),
                                        'decorators' => array(array('ViewHelper', array('escape' => true))),
										'class' => array('')					
                                    )
                                );
                                
                $genredropdown->setValue('');
                echo $genredropdown->render(); 
        	?></td>
      </tr>
      <tr>
        <td class="label"><?php echo $this->translate("billing_cardnumber_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><input type="text" size="19" maxlength="19" name="credit_card_number" id="creditCardNumber" value=""></td>
      </tr>
      <tr>
        <td class="label"><?php echo $this->translate("billing_cardexpirationdate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><?php		
                $genredropdown = new Zend_Form_Element_Select('expire_date_month',
                                    array(
										'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), getMonthsAsNumbers()),						
										'view' => new Zend_View(),
                                        'decorators' => array(array('ViewHelper', array('escape' => true))),
										'class' => array('')					
                                    )
                                );
                                
                $genredropdown->setValue('');
                echo $genredropdown->render(); 
        	?>
          <?php		
                $genredropdown = new Zend_Form_Element_Select('expire_date_year',
                                    array(
										'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), getFutureYears()),						
										'view' => new Zend_View(),
                                        'decorators' => array(array('ViewHelper', array('escape' => true))),
										'class' => array('')					
                                    )
                                );
                                
                $genredropdown->setValue('');
                echo $genredropdown->render(); 
        	?></td>
      </tr>
      <tr>
        <td class="label"><?php echo $this->translate("billing_cardverificationnumber_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><input type="text" class="numberfield" size="4" maxlength="4" name="cvv2_code" id="cvv2_code" value="">
          <a target="_blank" href="https://www.paypal.com/us/cgi-bin/webscr?cmd=p/acc/cvv_info_pop-outside"><img src="<?php echo $this->baseUrl("images/mini_cvv2.gif"); ?>" alt="What's this?" /></a>&nbsp;<a target="_blank" href="https://www.paypal.com/us/cgi-bin/webscr?cmd=p/acc/cvv_info_pop-outside"><span class="small">What's this?</span></a></td>
      </tr>
      <tr>
        <td colspan="2"><h2><?php echo $this->translate("billing_section_billing_address"); ?></h2></td>
      </tr>
      <tr>
        <td class="label"><?php echo $this->translate("billing_addressline1_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><textarea id="address1" name="address1" class="expanding"><?php echo $useraccount->getStreetAddress(); ?></textarea></td>
      </tr>
      <tr>
        <td class="label"><?php echo $this->translate("billing_addressline2_label"); ?>:</td>
        <td><textarea id="address2" name="address2" class="expanding"><?php echo $useraccount->getStreetAddress(); ?></textarea>
          <br />
          (optional)</td>
      </tr>
      <tr>
        <td class="label"><?php echo $this->translate("useraccount_country_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><?php
				$countrydropdown = new Zend_Form_Element_Select('country_code',
									array(
										'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), getCountries()),
										'view' => new Zend_View(),
										'decorators' => array('ViewHelper'),
										'class' => array('chzn-select','filterselect')
									)
								);
				$countrydropdown->setValue($useraccount->getCountry()); 
				echo $countrydropdown->render(); 
			  ?>
          <div id="country_error"></div></td>
      </tr>
    </tbody>
    <tbody id="usstates" class="hidden">
      <tr>
        <td class="label"><?php echo $this->translate("useraccount_state_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><?php
                    $statedropdown = new Zend_Form_Element_Select('state',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), getStates()),
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('chzn-select','filterselect')
                                        )
                                    );
                    $statedropdown->setValue($useraccount->getState()); 
                    echo $statedropdown->render(); 
                  ?>
          <div id="state_error"></div></td>
      </tr>
    </tbody>
    <tbody id="nonusstates" class="hidden">
      <tr>
        <td class="label"><?php echo $this->translate("useraccount_state_label"); ?>:</td>
        <td><input id="notusstate" name="notusstate" type="text" value="<?php echo $useraccount->getState(); ?>" /></td>
      </tr>
    </tbody>
    <tbody id="city_zip" class="hidden">
      <tr>
        <td class="label"><?php echo $this->translate("useraccount_city_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><input id="city" name="city" type="text" value="<?php echo $useraccount->getCity(); ?>" /></td>
      </tr>
      <tr>
        <td class="label"><?php echo $this->translate("billing_zipcode_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></td>
        <td><input type="text" maxlength="10" name="postal_code" id="postal_code" value="<?php echo $useraccount->getZipCode(); ?>"></td>
      </tr>
    </tbody>
  </table>
  <br />
  <table id="creditcardbuttons" class="hidden">
    <tr>
      <td colspan="2" style="padding-left:175px;"><a href="<?php echo $this->baseUrl('signup/step2/id/'.encode($useraccount->getID())); ?>" title="<?php echo $this->translate('global_button_back'); ?>"><?php echo $this->translate('global_button_back'); ?></a>&nbsp;&nbsp;
        <button id="creditcard" type="submit" class="positiveaction" title="<?php echo $this->translate('useraccount_button_checkoutproceed'); ?>"><img src="<?php echo $this->baseUrl('images/arrow_right.png'); ?>" /><?php echo $this->translate('useraccount_button_checkoutproceed'); ?></button>
        <input name="id" id="id" type="hidden" value="<?php echo encode($useraccount->getID()); ?>" /></td>
    </tr>
  </table>
  <table id="paypalbuttons" class="hidden">
    <tr>
      <td colspan="2" style="padding-left:175px;"><a href="<?php echo $this->baseUrl('signup/step2/id/'.encode($useraccount->getID())); ?>" title="<?php echo $this->translate('global_button_back'); ?>"><?php echo $this->translate('global_button_back'); ?></a>&nbsp;&nbsp;
        <button id="paypal" type="button" class="positiveaction" title="<?php echo $this->translate('useraccount_button_paypalproceed'); ?>"><img src="<?php echo $this->baseUrl('images/arrow_right.png'); ?>" /><?php echo $this->translate('useraccount_button_paypalproceed'); ?></button>
        <input name="id" id="id" type="hidden" value="<?php echo encode($useraccount->getID()); ?>" /></td>
    </tr>
  </table>
  <table id="trialbuttons" class="hidden">
    <tr>
      <td colspan="2" style="padding-left:175px;"><a href="<?php echo $this->baseUrl('signup/step2/id/'.encode($useraccount->getID())); ?>" title="<?php echo $this->translate('global_button_back'); ?>"><?php echo $this->translate('global_button_back'); ?></a>&nbsp;&nbsp; <a class="positiveaction"  href="<?php echo $this->baseUrl("signup/skippayment/id/".encode($useraccount->getID())); ?>" title="<?php echo $this->translate('useraccount_button_starttrial'); ?>" id="skip"><?php echo $this->translate('useraccount_button_starttrial'); ?></a>
        <input name="id" id="id" type="hidden" value="<?php echo encode($useraccount->getID()); ?>" /></td>
    </tr>
  </table>
</form>
<form action="<?php echo $config->paypal->serverurl; ?>" method="post" name="paymentform" id="paymentform">
  <!-- 
Buy Now buttons – <INPUT TYPE="hidden" name="cmd" value="_xclick">
Donate buttons – <INPUT TYPE="hidden" name="cmd" value="_donations">
Subscribe buttons – <INPUT TYPE="hidden" name="cmd" value="_xclick-subscriptions">
Shopping cart buttons – <INPUT TYPE="hidden" name="cmd" value="_cart">
-->
  <input type="hidden" name="cmd" value="_xclick-subscriptions" />
  <input type="hidden" name="business" value="<?php echo $config->paypal->receiveremail; ?>" />
  <input type="hidden" name="item_name" id="item_name" value="<?php echo "".$config->paypal->itemname; ?>" />
  <input type="hidden" name="item_number" id="item_number" value="<?php echo $config->paypal->itemnumber; ?>" />
  <input type="hidden" name="custom" id="custom" value="<?php echo $useraccount->getID(); ?>" />
  <input type="hidden" name="amount" id="amount" value="<?php echo $config->billing->writermonthlyrate; ?>" />
  <input type="hidden" name="quantity" id="quantity" value="1" />
  <input type="hidden" name="currency_code" value="USD" />
  <input type="hidden" name="return" value="<?php echo getPayPalReturnUrl()."/id/".encode($useraccount->getID()); ?>" />
  <input type="hidden" name="notify_url" value="<?php echo getPayPalNotifyUrl(); ?>" />
  <input type="hidden" name="cancel_return" value="<?php echo getPayPalCancelUrl()."/id/".encode($useraccount->getID()); ?>" />
  <input type="hidden" name="receiver_email" value="<?php echo $config->paypal->receiveremail; ?>" />
  <input type="hidden" name="no_shipping" value="1" />
  <input type="hidden" name="no_note" value="0" />
  <input type="hidden" name="ipaddress" value="<?php echo $_SERVER['REMOTE_ADDR']; ?>" />
  <!-- Recurring payments specific fields --> 
  <!-- Reference https://cms.paypal.com/us/cgi-bin/?cmd=_render-content&content_ID=developer/e_howto_html_Appx_websitestandard_htmlvariables --> 
  <!-- Trial period fields --> 
  <!-- https://www.paypalobjects.com/IntegrationCenter/ic_std-variable-ref-subscribe.html --> 
  <!--  <input type="hidden" name="a1" id="a1" value="0">
  <input type="hidden" name="p1" id="p1" value="1">
  <input type="hidden" name="t1" id="t1" value="M">--> 
  
  <!-- subscription fields -->
  <input type="hidden" name="a3" id="a3" value="<?php echo $config->billing->writermonthlyrate; ?>">
  <input type="hidden" name="p3" id="p3" value="1">
  <input type="hidden" name="t3" value="M">
  <input type="hidden" name="src" value="1">
  <input type="hidden" name="sra" value="1">
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
